baseurl = "https://blog.abhimankolte.com"
title = "AbeMurica's Technology blog"
theme = "hugo-coder"
languagecode = "en-us"
defaultcontentlanguage = "en"
disablePathToLower = true
enableRobotsTXT = true


[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Abhiman Kolte"
  info = "Software Engineer at LinkedIn"
  description = "Abhiman Kolte's personal website"
  keywords = "blog, developer, personal, software engineer, aws, gcp, java, python"
  tagline = "Architecting scalable cloud-native systems and leading high-performing engineering teams."
  highlights = [
    "Maintained 99.99% service availability",
    "Reduced Change Failure Rate by 60%",
    "Accelerated deployment velocity and safety for over 100 engineering teams"
  ]
  avatarurl = "images/profile.jpg"
  license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
  commit = "https://github.com/abhimanbhau/abhimanbhau.github.io/tree/"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/abhimanbhau"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "http://linkedin.com/in/abhimank"
[[params.social]]
  name = "Leetcode"
  icon = "fa-solid fa-code fa-2x"
  weight = 3
  url = "https://leetcode.com/abhimanbhau/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "post/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"